import type { DocEntry } from "./catalog";

const SEM_FONTE = {
  fonte: "Sem fonte oficial consultada neste protótipo",
  condicoes: "Confirmar na documentação da versão utilizada antes de implementar.",
};

/** Atalho para reduzir repetição mantendo todos os campos obrigatórios explícitos. */
function entry(e: DocEntry): DocEntry {
  return e;
}

export const catalogModulos: DocEntry[] = [
  /* ---------------- Módulo 2 — NF-e 55 ---------------- */
  entry({
    id: "m2.destinatario",
    modulo: "Módulo 2 — NF-e 55",
    tela: "Emissão de NF-e de Produtos",
    elemento: "Seleção de destinatário",
    nome: "Destinatário da operação",
    finalidade: "Identificar para quem a mercadoria é destinada e condicionar regras da operação.",
    tipo: "Referência a cadastro de pessoa (CNPJ ou CPF), com endereço e indicador de contribuinte",
    obrigatoriedade: "Obrigatório para a emissão",
    validacaoFront: [
      "Exigir seleção antes de habilitar a transmissão.",
      "Validar formato de documento quando digitado manualmente.",
    ],
    backendPython: [
      "Revalidar cadastro e situação do destinatário.",
      "Resolver indicador de IE, endereço completo e código de município.",
    ],
    mapeamentos: [
      { alvo: "Modelo interno", caminho: "nfe.destinatario", estado: "ilustrativo" },
      { alvo: "TecnoSpeed", caminho: "Grupo de destinatário do documento", estado: "pendente" },
    ],
    falhas: [
      { origem: "Erro local", situacao: "Destinatário não selecionado.", tratamento: "Bloquear a transmissão e focar o campo." },
      { origem: "Rejeição fiscal", situacao: "Dados cadastrais inconsistentes com a base oficial.", tratamento: "Exibir o retorno oficial sem reescrever o texto." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["Definir a origem do cadastro (ERP próprio ou consulta externa)."],
  }),
  entry({
    id: "m2.itens",
    modulo: "Módulo 2 — NF-e 55",
    tela: "Emissão de NF-e de Produtos",
    elemento: "Grade de itens",
    nome: "Itens da nota",
    finalidade: "Descrever os produtos transacionados, quantidades, preços e descontos.",
    tipo: "Coleção de itens com produto, NCM, unidade, quantidade, preço e desconto",
    obrigatoriedade: "Pelo menos um item",
    validacaoFront: [
      "Quantidade e preço maiores que zero.",
      "Desconto não pode superar o valor bruto do item.",
      "Cálculo de total por item feito na interface apenas para conferência visual.",
    ],
    backendPython: [
      "Recalcular todos os totais no servidor; o total enviado pelo front não é confiável.",
      "Resolver tributação por item conforme regras versionadas.",
    ],
    mapeamentos: [
      { alvo: "Modelo interno", caminho: "nfe.itens[]", estado: "ilustrativo" },
      { alvo: "TecnoSpeed", caminho: "Grupo de detalhamento de produtos", estado: "pendente" },
    ],
    exemplo: `// Modelo interno ilustrativo
{ "codigo": "SKU-1001", "ncm": "72091500", "quantidade": 40, "valorUnitario": 210.50, "desconto": 0 }`,
    falhas: [
      { origem: "Erro local", situacao: "Item com quantidade zero ou negativa.", tratamento: "Destacar a linha e impedir a transmissão." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),
  entry({
    id: "m2.cfop",
    modulo: "Módulo 2 — NF-e 55",
    tela: "Emissão de NF-e de Produtos",
    elemento: "CFOP sugerido",
    nome: "Sugestão de CFOP",
    finalidade: "Acelerar o preenchimento sugerindo um código provável para a operação.",
    tipo: "Código numérico de 4 posições",
    obrigatoriedade: "Obrigatório por item na emissão real",
    validacaoFront: [
      "A sugestão é heurística e deve permanecer editável.",
      "Nunca apresentar a sugestão como decisão fiscal definitiva.",
    ],
    backendPython: [
      "Determinar o CFOP a partir de regras versionadas: natureza, finalidade, origem da mercadoria, destino e regime.",
      "Rejeitar o CFOP enviado pelo front quando conflitar com a regra vigente.",
    ],
    mapeamentos: [
      { alvo: "Modelo interno", caminho: "nfe.itens[].cfop", estado: "ilustrativo" },
    ],
    falhas: [
      { origem: "Rejeição fiscal", situacao: "CFOP incompatível com a operação declarada.", tratamento: "Apresentar o retorno oficial e permitir correção." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: [
      "A heurística do protótipo (5101/5102/6101/6102) não cobre devolução, remessa, industrialização, exportação e demais operações.",
    ],
  }),
  entry({
    id: "m2.previa",
    modulo: "Módulo 2 — NF-e 55",
    tela: "Emissão de NF-e de Produtos",
    elemento: "Painel de prévia tributária",
    nome: "Prévia de tributos",
    finalidade: "Dar ao operador uma ordem de grandeza antes da transmissão.",
    tipo: "Conjunto de valores estimados por grupo tributário",
    obrigatoriedade: "Informativo",
    validacaoFront: [
      "Sempre rotulado como estimativa.",
      "Não pode ser usado como base para lançamento contábil.",
    ],
    backendPython: [
      "Calcular tributos com regras versionadas, vigência e parâmetros do contribuinte.",
      "Devolver ao front o resultado calculado, não a fórmula.",
    ],
    mapeamentos: [
      { alvo: "Modelo interno", caminho: "nfe.previaTributaria", estado: "ilustrativo" },
    ],
    falhas: [
      { origem: "Erro local", situacao: "Prévia divergindo do cálculo do back-end.", tratamento: "Exibir sempre o valor do back-end como autoritativo." },
    ],
    estado: "ilustrativo",
    rastreabilidade: {
      fonte: "Percentuais arbitrários definidos no próprio protótipo",
      condicoes: "Nenhuma alíquota aqui é oficial.",
    },
    pendencias: ["Substituir os percentuais de cenário por cálculo do back-end."],
  }),
  entry({
    id: "m2.transmitir",
    modulo: "Módulo 2 — NF-e 55",
    tela: "Emissão de NF-e de Produtos",
    elemento: "Ação de transmissão",
    nome: "Transmissão do documento",
    finalidade: "Enviar o documento montado para autorização.",
    tipo: "Ação assíncrona com resultado tipado",
    obrigatoriedade: "Ação final do fluxo",
    validacaoFront: [
      "Bloquear enquanto houver problema de validação local.",
      "Impedir duplo clique gerando duas transmissões.",
    ],
    backendPython: [
      "Montar e assinar o documento; o front nunca vê o certificado.",
      "Garantir idempotência por identificador de rascunho.",
      "Persistir protocolo e retorno bruto.",
    ],
    mapeamentos: [
      { alvo: "Modelo interno", caminho: "emissao.transmitir()", estado: "ilustrativo" },
      { alvo: "TecnoSpeed", caminho: "Serviço de envio de NF-e", estado: "pendente" },
    ],
    falhas: [
      { origem: "Erro local", situacao: "Campos obrigatórios ausentes.", tratamento: "Listar os campos e focar o primeiro." },
      { origem: "Erro do provedor", situacao: "Indisponibilidade ou tempo de resposta excedido.", tratamento: "Permitir nova tentativa idempotente." },
      { origem: "Rejeição fiscal", situacao: "Documento recusado na autorização.", tratamento: "Exibir código e descrição oficiais, sem paráfrase." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),

  /* ---------------- Módulo 3 — NFC-e 65 ---------------- */
  entry({
    id: "m3.itens",
    modulo: "Módulo 3 — NFC-e 65",
    tela: "PDV",
    elemento: "Venda rápida",
    nome: "Inclusão de itens no cupom",
    finalidade: "Permitir lançamento rápido por código de barras ou seleção, com teclado.",
    tipo: "Coleção de itens com produto e quantidade",
    obrigatoriedade: "Pelo menos um item por cupom",
    validacaoFront: [
      "Enter confirma o item sem uso de mouse.",
      "Quantidade maior que zero.",
    ],
    backendPython: ["Recalcular preços e totais; preço do front é apenas exibição."],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "nfce.itens[]", estado: "ilustrativo" }],
    falhas: [
      { origem: "Erro local", situacao: "Código lido não encontrado no cadastro.", tratamento: "Sinalizar sem travar o caixa e manter o foco no campo." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),
  entry({
    id: "m3.pagamento",
    modulo: "Módulo 3 — NFC-e 65",
    tela: "PDV",
    elemento: "Fechamento e pagamento",
    nome: "Formas de pagamento",
    finalidade: "Registrar como a venda foi paga e calcular troco.",
    tipo: "Lista de pagamentos com meio e valor",
    obrigatoriedade: "Obrigatório no fechamento",
    validacaoFront: [
      "Valor recebido em dinheiro não pode ser menor que o total.",
      "Troco calculado apenas para conferência do operador.",
    ],
    backendPython: [
      "Validar a composição dos pagamentos e os códigos de meio de pagamento exigidos.",
      "Integrar com o adquirente quando houver pagamento eletrônico.",
    ],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "nfce.pagamentos[]", estado: "ilustrativo" }],
    falhas: [
      { origem: "Erro local", situacao: "Soma dos pagamentos diferente do total.", tratamento: "Bloquear o fechamento com mensagem objetiva." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["Os códigos oficiais de meio de pagamento não foram fixados no protótipo."],
  }),
  entry({
    id: "m3.contingencia",
    modulo: "Módulo 3 — NFC-e 65",
    tela: "PDV",
    elemento: "Alternância de conexão simulada",
    nome: "Cenário de contingência",
    finalidade: "Demonstrar o comportamento do caixa quando a transmissão não é possível.",
    tipo: "Estado booleano de conectividade simulada",
    obrigatoriedade: "Recurso de demonstração",
    validacaoFront: ["A venda não pode ser perdida quando a transmissão falha."],
    backendPython: [
      "Definir a modalidade de contingência aplicável e a regra de transmissão posterior.",
      "Controlar numeração e integridade dos documentos pendentes.",
    ],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "pdv.online", estado: "ilustrativo" }],
    falhas: [
      { origem: "Erro do provedor", situacao: "Sem conexão com o serviço de autorização.", tratamento: "Enfileirar e sinalizar pendência de forma visível." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: [
      "Modalidades de contingência, prazos e obrigações variam por UF — nenhuma regra foi fixada aqui.",
    ],
  }),
  entry({
    id: "m3.fila",
    modulo: "Módulo 3 — NFC-e 65",
    tela: "PDV",
    elemento: "Fila de contingência",
    nome: "Documentos pendentes de transmissão",
    finalidade: "Tornar visível o que ainda não foi autorizado.",
    tipo: "Coleção de vendas pendentes",
    obrigatoriedade: "Sempre visível quando houver pendência",
    validacaoFront: ["Processamento da fila só liberado com conexão restabelecida."],
    backendPython: [
      "Persistir a fila fora do navegador.",
      "Transmitir em ordem e tratar duplicidade por identificador próprio.",
    ],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "pdv.fila[]", estado: "ilustrativo" }],
    falhas: [
      { origem: "Erro do provedor", situacao: "Falha ao reprocessar a fila.", tratamento: "Manter os itens na fila e registrar o motivo." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["No protótipo a fila vive apenas na memória da página."],
  }),

  /* ---------------- Módulo 4 — NFS-e ---------------- */
  entry({
    id: "m4.cliente",
    modulo: "Módulo 4 — NFS-e",
    tela: "Emissão de NFS-e",
    elemento: "Cliente",
    nome: "Tomador do serviço",
    finalidade: "Identificar quem contrata o serviço.",
    tipo: "Referência a cadastro de pessoa",
    obrigatoriedade: "Obrigatório",
    validacaoFront: ["Exigir seleção antes de emitir."],
    backendPython: ["Completar endereço e município do tomador exigidos pelo padrão municipal."],
    mapeamentos: [
      { alvo: "Modelo interno", caminho: "nfse.tomador", estado: "ilustrativo" },
      { alvo: "PlugNotas", caminho: "Grupo de tomador do serviço", estado: "pendente" },
    ],
    falhas: [
      { origem: "Erro do provedor", situacao: "Cadastro rejeitado pelo padrão do município.", tratamento: "Exibir o retorno do provedor sem reinterpretar." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),
  entry({
    id: "m4.servico",
    modulo: "Módulo 4 — NFS-e",
    tela: "Emissão de NFS-e",
    elemento: "Serviço",
    nome: "Serviço prestado",
    finalidade: "Classificar o serviço para fins de tributação municipal.",
    tipo: "Código de serviço + descrição",
    obrigatoriedade: "Obrigatório",
    validacaoFront: ["Seleção obrigatória; o código interno não substitui o código municipal."],
    backendPython: [
      "Traduzir o código interno para o código exigido pelo município de incidência.",
      "Manter versionamento da lista por município.",
    ],
    mapeamentos: [
      { alvo: "Modelo interno", caminho: "nfse.servico.codigoInterno", estado: "ilustrativo" },
      { alvo: "PlugNotas", caminho: "Código de serviço municipal", estado: "pendente" },
    ],
    falhas: [
      { origem: "Rejeição fiscal", situacao: "Código não aceito pelo município.", tratamento: "Exibir a mensagem oficial e permitir nova escolha." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["Os códigos exibidos no protótipo são fictícios e não seguem a lista oficial."],
  }),
  entry({
    id: "m4.valor",
    modulo: "Módulo 4 — NFS-e",
    tela: "Emissão de NFS-e",
    elemento: "Valor do serviço",
    nome: "Valor da prestação",
    finalidade: "Base para a apuração do imposto municipal.",
    tipo: "Valor monetário",
    obrigatoriedade: "Obrigatório e maior que zero",
    validacaoFront: ["Impedir valor zero ou negativo."],
    backendPython: ["Recalcular base, deduções e retenções conforme regras do município."],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "nfse.valorServico", estado: "ilustrativo" }],
    falhas: [{ origem: "Erro local", situacao: "Valor não informado.", tratamento: "Bloquear a emissão." }],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),
  entry({
    id: "m4.descricao",
    modulo: "Módulo 4 — NFS-e",
    tela: "Emissão de NFS-e",
    elemento: "Descrição do serviço",
    nome: "Discriminação do serviço",
    finalidade: "Descrever o que foi prestado, conteúdo lido pelo tomador e pela fiscalização.",
    tipo: "Texto livre",
    obrigatoriedade: "Obrigatório na maioria dos padrões municipais",
    validacaoFront: ["Mínimo de caracteres para evitar descrição vazia ou genérica."],
    backendPython: ["Aplicar limite de tamanho e sanitização conforme o padrão do município."],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "nfse.descricao", estado: "ilustrativo" }],
    falhas: [
      { origem: "Erro do provedor", situacao: "Texto acima do limite aceito.", tratamento: "Informar o limite real retornado pelo provedor." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["Limite de caracteres varia por município e não foi fixado."],
  }),
  entry({
    id: "m4.avancada",
    modulo: "Módulo 4 — NFS-e",
    tela: "Emissão de NFS-e",
    elemento: "Bloco de tributação avançada",
    nome: "Campos opcionais de tributação",
    finalidade: "Manter a tela enxuta no caso comum, sem esconder o que é necessário em casos específicos.",
    tipo: "Grupo recolhido com alíquota, deduções, retenção e observações",
    obrigatoriedade: "Opcional no protótipo",
    validacaoFront: [
      "Permanecer recolhido por padrão.",
      "Abrir automaticamente quando o back-end apontar problema em um destes campos.",
    ],
    backendPython: [
      "Determinar alíquota, retenções e regime conforme município e cadastro do prestador.",
      "Ignorar valores enviados pelo front quando conflitarem com a regra vigente.",
    ],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "nfse.tributacao", estado: "ilustrativo" }],
    falhas: [
      { origem: "Rejeição fiscal", situacao: "Retenção incompatível com o cadastro do tomador.", tratamento: "Abrir o bloco e destacar o campo apontado." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["A alíquota exibida é de cenário; não representa nenhum município."],
  }),

  /* ---------------- Módulo 5 — CT-e 57 ---------------- */
  entry({
    id: "m5.xml",
    modulo: "Módulo 5 — CT-e 57",
    tela: "Emissão de CT-e de carga",
    elemento: "Área de arrastar e soltar XML",
    nome: "Vinculação de documentos transportados",
    finalidade: "Associar as NF-e que compõem a carga ao conhecimento de transporte.",
    tipo: "Arquivos XML + coleção de documentos vinculados",
    obrigatoriedade: "Pelo menos um documento",
    validacaoFront: [
      "Aceitar apenas arquivos .xml.",
      "Leitura no navegador é demonstrativa e serve para preencher a tela.",
      "Nenhum arquivo é enviado a servidores neste protótipo.",
    ],
    backendPython: [
      "Validar estrutura, assinatura e situação de cada documento vinculado.",
      "Extrair chave, valores e pesos de forma autoritativa.",
      "Rejeitar o vínculo quando o documento não estiver autorizado.",
    ],
    mapeamentos: [
      { alvo: "Modelo interno", caminho: "cte.documentos[]", estado: "ilustrativo" },
      { alvo: "TecnoSpeed", caminho: "Grupo de documentos transportados", estado: "pendente" },
    ],
    falhas: [
      { origem: "Erro local", situacao: "Arquivo ilegível ou sem chave reconhecível.", tratamento: "Marcar a linha como demonstrativa e exigir revisão." },
      { origem: "Erro do provedor", situacao: "Documento não localizado na base do provedor.", tratamento: "Informar sem remover o vínculo automaticamente." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["A extração por expressão regular não substitui um parser validado no back-end."],
  }),
  entry({
    id: "m5.partes",
    modulo: "Módulo 5 — CT-e 57",
    tela: "Emissão de CT-e de carga",
    elemento: "Remetente e destinatário",
    nome: "Partes da prestação",
    finalidade: "Identificar os envolvidos no transporte e permitir determinar o tomador.",
    tipo: "Referências a cadastros de pessoa",
    obrigatoriedade: "Obrigatório",
    validacaoFront: ["Exigir preenchimento antes de transmitir."],
    backendPython: [
      "Determinar o tomador do serviço conforme a regra aplicável ao caso.",
      "Completar endereços e códigos de município.",
    ],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "cte.partes", estado: "ilustrativo" }],
    falhas: [
      { origem: "Rejeição fiscal", situacao: "Tomador incompatível com a operação declarada.", tratamento: "Exibir o retorno oficial." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["A escolha do tomador não é feita pelo protótipo."],
  }),
  entry({
    id: "m5.frete",
    modulo: "Módulo 5 — CT-e 57",
    tela: "Emissão de CT-e de carga",
    elemento: "Composição do frete",
    nome: "Valor da prestação",
    finalidade: "Informar o preço do serviço de transporte e seus componentes.",
    tipo: "Valores monetários por componente",
    obrigatoriedade: "Obrigatório e maior que zero",
    validacaoFront: ["Somatório dos componentes conferido apenas para exibição."],
    backendPython: [
      "Validar componentes aceitos e recalcular o total da prestação.",
      "Calcular a tributação do serviço conforme regras versionadas.",
    ],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "cte.prestacao", estado: "ilustrativo" }],
    falhas: [
      { origem: "Erro local", situacao: "Frete zerado.", tratamento: "Bloquear a transmissão." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["Nomes e códigos dos componentes de frete não foram fixados."],
  }),

  /* ---------------- Módulo 6 — CT-e OS 67 ---------------- */
  entry({
    id: "m6.modalidade",
    modulo: "Módulo 6 — CT-e OS 67",
    tela: "Emissão de CT-e OS",
    elemento: "Abas de modalidade",
    nome: "Modalidade do serviço",
    finalidade: "Separar transporte de pessoas de transporte de valores, que exigem dados distintos.",
    tipo: "Enum de modalidade",
    obrigatoriedade: "Obrigatório",
    validacaoFront: ["Trocar de modalidade não pode apagar dados já digitados sem aviso."],
    backendPython: ["Selecionar o conjunto de campos exigido para cada modalidade."],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "cteOs.modalidade", estado: "ilustrativo" }],
    falhas: [
      { origem: "Erro local", situacao: "Campos da modalidade incompletos.", tratamento: "Mostrar a aba onde está o problema." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),
  entry({
    id: "m6.tomador",
    modulo: "Módulo 6 — CT-e OS 67",
    tela: "Emissão de CT-e OS",
    elemento: "Tomador do serviço",
    nome: "Contratante do serviço",
    finalidade: "Identificar quem contrata a prestação.",
    tipo: "Referência a cadastro de pessoa",
    obrigatoriedade: "Obrigatório",
    validacaoFront: ["Exigir seleção antes de transmitir."],
    backendPython: ["Completar dados cadastrais e validar situação."],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "cteOs.tomador", estado: "ilustrativo" }],
    falhas: [{ origem: "Erro local", situacao: "Tomador ausente.", tratamento: "Bloquear a transmissão." }],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),
  entry({
    id: "m6.passageiros",
    modulo: "Módulo 6 — CT-e OS 67",
    tela: "Emissão de CT-e OS",
    elemento: "Quantidade de passageiros",
    nome: "Transporte de pessoas",
    finalidade: "Dimensionar a prestação no transporte de pessoas.",
    tipo: "Número inteiro",
    obrigatoriedade: "Obrigatório nesta modalidade",
    validacaoFront: ["Valor maior que zero."],
    backendPython: ["Confirmar quais dados de passageiros o modelo exige."],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "cteOs.passageiros", estado: "ilustrativo" }],
    falhas: [{ origem: "Erro local", situacao: "Quantidade inválida.", tratamento: "Bloquear e focar o campo." }],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["Não foi confirmado se o modelo exige identificação individual dos passageiros."],
  }),
  entry({
    id: "m6.malotes",
    modulo: "Módulo 6 — CT-e OS 67",
    tela: "Emissão de CT-e OS",
    elemento: "Grade de malotes",
    nome: "Transporte de valores",
    finalidade: "Relacionar os malotes transportados e os valores declarados.",
    tipo: "Coleção de malotes com número, descrição, quantidade e valor",
    obrigatoriedade: "Obrigatório nesta modalidade",
    validacaoFront: ["Número de identificação obrigatório por malote."],
    backendPython: ["Confirmar a estrutura exigida e os limites de quantidade e valor."],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "cteOs.malotes[]", estado: "ilustrativo" }],
    falhas: [
      { origem: "Erro local", situacao: "Malote sem número.", tratamento: "Destacar a linha incompleta." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["A grade é uma proposta de layout, não um espelho do leiaute oficial."],
  }),
  entry({
    id: "m6.prestacao",
    modulo: "Módulo 6 — CT-e OS 67",
    tela: "Emissão de CT-e OS",
    elemento: "Valor da prestação",
    nome: "Preço do serviço",
    finalidade: "Informar o valor cobrado pela prestação.",
    tipo: "Valor monetário",
    obrigatoriedade: "Obrigatório",
    validacaoFront: ["Maior que zero."],
    backendPython: ["Recalcular total e tributos conforme regra vigente."],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "cteOs.valorPrestacao", estado: "ilustrativo" }],
    falhas: [{ origem: "Erro local", situacao: "Valor zerado.", tratamento: "Bloquear a transmissão." }],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),

  /* ---------------- Módulo 7 — MDF-e 58 ---------------- */
  entry({
    id: "m7.documentos",
    modulo: "Módulo 7 — MDF-e 58",
    tela: "Emissão de MDF-e",
    elemento: "Seleção de documentos",
    nome: "Documentos manifestados",
    finalidade: "Relacionar os CT-e e NF-e que acompanham a viagem.",
    tipo: "Coleção de chaves de acesso",
    obrigatoriedade: "Pelo menos um documento",
    validacaoFront: ["Impedir transmissão sem nenhum documento selecionado."],
    backendPython: [
      "Validar situação de cada documento antes de incluir no manifesto.",
      "Agrupar os documentos por município de descarregamento.",
    ],
    mapeamentos: [
      { alvo: "Modelo interno", caminho: "mdfe.documentos[]", estado: "ilustrativo" },
      { alvo: "TecnoSpeed", caminho: "Grupo de documentos do manifesto", estado: "pendente" },
    ],
    falhas: [
      { origem: "Rejeição fiscal", situacao: "Documento cancelado ou não autorizado incluído no manifesto.", tratamento: "Exibir o retorno oficial e destacar a linha." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),
  entry({
    id: "m7.condutor",
    modulo: "Módulo 7 — MDF-e 58",
    tela: "Emissão de MDF-e",
    elemento: "Motorista",
    nome: "Condutor da viagem",
    finalidade: "Identificar quem conduz o veículo no trajeto manifestado.",
    tipo: "Nome e documento do condutor",
    obrigatoriedade: "Obrigatório no modal rodoviário",
    validacaoFront: ["Exigir seleção antes de transmitir."],
    backendPython: ["Validar o documento do condutor conforme exigência do modelo."],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "mdfe.condutor", estado: "ilustrativo" }],
    falhas: [{ origem: "Erro local", situacao: "Condutor não informado.", tratamento: "Bloquear a transmissão." }],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),
  entry({
    id: "m7.veiculo",
    modulo: "Módulo 7 — MDF-e 58",
    tela: "Emissão de MDF-e",
    elemento: "Veículo e reboques",
    nome: "Composição veicular",
    finalidade: "Descrever a tração e os reboques usados no transporte.",
    tipo: "Placa, UF, tara e lista de reboques",
    obrigatoriedade: "Obrigatório no modal rodoviário",
    validacaoFront: ["Reboques listados a partir do veículo escolhido."],
    backendPython: [
      "Validar placas, tara e capacidade conforme cadastro.",
      "Confirmar o limite de reboques aceito pelo modelo.",
    ],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "mdfe.veiculo", estado: "ilustrativo" }],
    falhas: [
      { origem: "Rejeição fiscal", situacao: "Placa inválida ou composição não aceita.", tratamento: "Exibir o retorno oficial sem reescrevê-lo." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
  }),
  entry({
    id: "m7.percurso",
    modulo: "Módulo 7 — MDF-e 58",
    tela: "Emissão de MDF-e",
    elemento: "UFs de percurso",
    nome: "Percurso da viagem",
    finalidade: "Declarar as unidades federativas atravessadas entre origem e destino.",
    tipo: "Lista ordenada de UFs",
    obrigatoriedade: "Condicional",
    validacaoFront: ["Seleção livre no protótipo, sem checagem de contiguidade."],
    backendPython: [
      "Validar a coerência do percurso com origem e destino.",
      "Aplicar a regra de obrigatoriedade conforme o trajeto.",
    ],
    mapeamentos: [{ alvo: "Modelo interno", caminho: "mdfe.percurso[]", estado: "ilustrativo" }],
    falhas: [
      { origem: "Rejeição fiscal", situacao: "Percurso incompatível com origem e destino.", tratamento: "Exibir o retorno oficial e permitir correção." },
    ],
    estado: "ilustrativo",
    rastreabilidade: SEM_FONTE,
    pendencias: ["A regra de contiguidade entre UFs não foi implementada nem confirmada."],
  }),
];
