/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademiaRouteImport } from './routes/academia'
import { Route as CenariosRouteImport } from './routes/cenarios'
import { Route as ComeceAquiRouteImport } from './routes/comece-aqui'
import { Route as ConhecimentoRouteImport } from './routes/conhecimento'
import { Route as CstatRouteImport } from './routes/cstat'
import { Route as CteRouteImport } from './routes/cte'
import { Route as CteOsRouteImport } from './routes/cte-os'
import { Route as DebuggerRouteImport } from './routes/debugger'
import { Route as FontesRouteImport } from './routes/fontes'
import { Route as IncidentesRouteImport } from './routes/incidentes'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MathLabRouteImport } from './routes/math-lab'
import { Route as MatrizRouteImport } from './routes/matriz'
import { Route as MdfeRouteImport } from './routes/mdfe'
import { Route as NfceRouteImport } from './routes/nfce'
import { Route as NfeRouteImport } from './routes/nfe'
import { Route as NfseRouteImport } from './routes/nfse'
import { Route as QualidadeRouteImport } from './routes/qualidade'
import { Route as ReformaRouteImport } from './routes/reforma'
import { Route as RegressaoRouteImport } from './routes/regressao'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as XmlLabRouteImport } from './routes/xml-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaRoute = AcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const CenariosRoute = CenariosRouteImport.update({
  id: '/cenarios',
  path: '/cenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeceAquiRoute = ComeceAquiRouteImport.update({
  id: '/comece-aqui',
  path: '/comece-aqui',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoRoute = ConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CstatRoute = CstatRouteImport.update({
  id: '/cstat',
  path: '/cstat',
  getParentRoute: () => rootRouteImport,
} as any)
const CteRoute = CteRouteImport.update({
  id: '/cte',
  path: '/cte',
  getParentRoute: () => rootRouteImport,
} as any)
const CteOsRoute = CteOsRouteImport.update({
  id: '/cte-os',
  path: '/cte-os',
  getParentRoute: () => rootRouteImport,
} as any)
const DebuggerRoute = DebuggerRouteImport.update({
  id: '/debugger',
  path: '/debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesRoute = FontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentesRoute = IncidentesRouteImport.update({
  id: '/incidentes',
  path: '/incidentes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MathLabRoute = MathLabRouteImport.update({
  id: '/math-lab',
  path: '/math-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizRoute = MatrizRouteImport.update({
  id: '/matriz',
  path: '/matriz',
  getParentRoute: () => rootRouteImport,
} as any)
const MdfeRoute = MdfeRouteImport.update({
  id: '/mdfe',
  path: '/mdfe',
  getParentRoute: () => rootRouteImport,
} as any)
const NfceRoute = NfceRouteImport.update({
  id: '/nfce',
  path: '/nfce',
  getParentRoute: () => rootRouteImport,
} as any)
const NfeRoute = NfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => rootRouteImport,
} as any)
const NfseRoute = NfseRouteImport.update({
  id: '/nfse',
  path: '/nfse',
  getParentRoute: () => rootRouteImport,
} as any)
const QualidadeRoute = QualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformaRoute = ReformaRouteImport.update({
  id: '/reforma',
  path: '/reforma',
  getParentRoute: () => rootRouteImport,
} as any)
const RegressaoRoute = RegressaoRouteImport.update({
  id: '/regressao',
  path: '/regressao',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlLabRoute = XmlLabRouteImport.update({
  id: '/xml-lab',
  path: '/xml-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/cenarios': typeof CenariosRoute
  '/comece-aqui': typeof ComeceAquiRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/cstat': typeof CstatRoute
  '/cte': typeof CteRoute
  '/cte-os': typeof CteOsRoute
  '/debugger': typeof DebuggerRoute
  '/fontes': typeof FontesRoute
  '/incidentes': typeof IncidentesRoute
  '/mapa': typeof MapaRoute
  '/math-lab': typeof MathLabRoute
  '/matriz': typeof MatrizRoute
  '/mdfe': typeof MdfeRoute
  '/nfce': typeof NfceRoute
  '/nfe': typeof NfeRoute
  '/nfse': typeof NfseRoute
  '/qualidade': typeof QualidadeRoute
  '/reforma': typeof ReformaRoute
  '/regressao': typeof RegressaoRoute
  '/suporte': typeof SuporteRoute
  '/xml-lab': typeof XmlLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/cenarios': typeof CenariosRoute
  '/comece-aqui': typeof ComeceAquiRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/cstat': typeof CstatRoute
  '/cte': typeof CteRoute
  '/cte-os': typeof CteOsRoute
  '/debugger': typeof DebuggerRoute
  '/fontes': typeof FontesRoute
  '/incidentes': typeof IncidentesRoute
  '/mapa': typeof MapaRoute
  '/math-lab': typeof MathLabRoute
  '/matriz': typeof MatrizRoute
  '/mdfe': typeof MdfeRoute
  '/nfce': typeof NfceRoute
  '/nfe': typeof NfeRoute
  '/nfse': typeof NfseRoute
  '/qualidade': typeof QualidadeRoute
  '/reforma': typeof ReformaRoute
  '/regressao': typeof RegressaoRoute
  '/suporte': typeof SuporteRoute
  '/xml-lab': typeof XmlLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/cenarios': typeof CenariosRoute
  '/comece-aqui': typeof ComeceAquiRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/cstat': typeof CstatRoute
  '/cte': typeof CteRoute
  '/cte-os': typeof CteOsRoute
  '/debugger': typeof DebuggerRoute
  '/fontes': typeof FontesRoute
  '/incidentes': typeof IncidentesRoute
  '/mapa': typeof MapaRoute
  '/math-lab': typeof MathLabRoute
  '/matriz': typeof MatrizRoute
  '/mdfe': typeof MdfeRoute
  '/nfce': typeof NfceRoute
  '/nfe': typeof NfeRoute
  '/nfse': typeof NfseRoute
  '/qualidade': typeof QualidadeRoute
  '/reforma': typeof ReformaRoute
  '/regressao': typeof RegressaoRoute
  '/suporte': typeof SuporteRoute
  '/xml-lab': typeof XmlLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academia'
    | '/cenarios'
    | '/comece-aqui'
    | '/conhecimento'
    | '/cstat'
    | '/cte'
    | '/cte-os'
    | '/debugger'
    | '/fontes'
    | '/incidentes'
    | '/mapa'
    | '/math-lab'
    | '/matriz'
    | '/mdfe'
    | '/nfce'
    | '/nfe'
    | '/nfse'
    | '/qualidade'
    | '/reforma'
    | '/regressao'
    | '/suporte'
    | '/xml-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academia'
    | '/cenarios'
    | '/comece-aqui'
    | '/conhecimento'
    | '/cstat'
    | '/cte'
    | '/cte-os'
    | '/debugger'
    | '/fontes'
    | '/incidentes'
    | '/mapa'
    | '/math-lab'
    | '/matriz'
    | '/mdfe'
    | '/nfce'
    | '/nfe'
    | '/nfse'
    | '/qualidade'
    | '/reforma'
    | '/regressao'
    | '/suporte'
    | '/xml-lab'
  id:
    | '__root__'
    | '/'
    | '/academia'
    | '/cenarios'
    | '/comece-aqui'
    | '/conhecimento'
    | '/cstat'
    | '/cte'
    | '/cte-os'
    | '/debugger'
    | '/fontes'
    | '/incidentes'
    | '/mapa'
    | '/math-lab'
    | '/matriz'
    | '/mdfe'
    | '/nfce'
    | '/nfe'
    | '/nfse'
    | '/qualidade'
    | '/reforma'
    | '/regressao'
    | '/suporte'
    | '/xml-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiaRoute: typeof AcademiaRoute
  CenariosRoute: typeof CenariosRoute
  ComeceAquiRoute: typeof ComeceAquiRoute
  ConhecimentoRoute: typeof ConhecimentoRoute
  CstatRoute: typeof CstatRoute
  CteRoute: typeof CteRoute
  CteOsRoute: typeof CteOsRoute
  DebuggerRoute: typeof DebuggerRoute
  FontesRoute: typeof FontesRoute
  IncidentesRoute: typeof IncidentesRoute
  MapaRoute: typeof MapaRoute
  MathLabRoute: typeof MathLabRoute
  MatrizRoute: typeof MatrizRoute
  MdfeRoute: typeof MdfeRoute
  NfceRoute: typeof NfceRoute
  NfeRoute: typeof NfeRoute
  NfseRoute: typeof NfseRoute
  QualidadeRoute: typeof QualidadeRoute
  ReformaRoute: typeof ReformaRoute
  RegressaoRoute: typeof RegressaoRoute
  SuporteRoute: typeof SuporteRoute
  XmlLabRoute: typeof XmlLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia': {
      id: '/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenarios': {
      id: '/cenarios'
      path: '/cenarios'
      fullPath: '/cenarios'
      preLoaderRoute: typeof CenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comece-aqui': {
      id: '/comece-aqui'
      path: '/comece-aqui'
      fullPath: '/comece-aqui'
      preLoaderRoute: typeof ComeceAquiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento': {
      id: '/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof ConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cstat': {
      id: '/cstat'
      path: '/cstat'
      fullPath: '/cstat'
      preLoaderRoute: typeof CstatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cte': {
      id: '/cte'
      path: '/cte'
      fullPath: '/cte'
      preLoaderRoute: typeof CteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cte-os': {
      id: '/cte-os'
      path: '/cte-os'
      fullPath: '/cte-os'
      preLoaderRoute: typeof CteOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debugger': {
      id: '/debugger'
      path: '/debugger'
      fullPath: '/debugger'
      preLoaderRoute: typeof DebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes': {
      id: '/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof FontesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidentes': {
      id: '/incidentes'
      path: '/incidentes'
      fullPath: '/incidentes'
      preLoaderRoute: typeof IncidentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math-lab': {
      id: '/math-lab'
      path: '/math-lab'
      fullPath: '/math-lab'
      preLoaderRoute: typeof MathLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriz': {
      id: '/matriz'
      path: '/matriz'
      fullPath: '/matriz'
      preLoaderRoute: typeof MatrizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdfe': {
      id: '/mdfe'
      path: '/mdfe'
      fullPath: '/mdfe'
      preLoaderRoute: typeof MdfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfce': {
      id: '/nfce'
      path: '/nfce'
      fullPath: '/nfce'
      preLoaderRoute: typeof NfceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfe': {
      id: '/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof NfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfse': {
      id: '/nfse'
      path: '/nfse'
      fullPath: '/nfse'
      preLoaderRoute: typeof NfseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualidade': {
      id: '/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof QualidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforma': {
      id: '/reforma'
      path: '/reforma'
      fullPath: '/reforma'
      preLoaderRoute: typeof ReformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regressao': {
      id: '/regressao'
      path: '/regressao'
      fullPath: '/regressao'
      preLoaderRoute: typeof RegressaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-lab': {
      id: '/xml-lab'
      path: '/xml-lab'
      fullPath: '/xml-lab'
      preLoaderRoute: typeof XmlLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiaRoute: AcademiaRoute,
  CenariosRoute: CenariosRoute,
  ComeceAquiRoute: ComeceAquiRoute,
  ConhecimentoRoute: ConhecimentoRoute,
  CstatRoute: CstatRoute,
  CteRoute: CteRoute,
  CteOsRoute: CteOsRoute,
  DebuggerRoute: DebuggerRoute,
  FontesRoute: FontesRoute,
  IncidentesRoute: IncidentesRoute,
  MapaRoute: MapaRoute,
  MathLabRoute: MathLabRoute,
  MatrizRoute: MatrizRoute,
  MdfeRoute: MdfeRoute,
  NfceRoute: NfceRoute,
  NfeRoute: NfeRoute,
  NfseRoute: NfseRoute,
  QualidadeRoute: QualidadeRoute,
  ReformaRoute: ReformaRoute,
  RegressaoRoute: RegressaoRoute,
  SuporteRoute: SuporteRoute,
  XmlLabRoute: XmlLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
