/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CenariosRouteImport } from './routes/cenarios'
import { Route as ConhecimentoRouteImport } from './routes/conhecimento'
import { Route as CstatRouteImport } from './routes/cstat'
import { Route as CteRouteImport } from './routes/cte'
import { Route as CteOsRouteImport } from './routes/cte-os'
import { Route as DebuggerRouteImport } from './routes/debugger'
import { Route as MathLabRouteImport } from './routes/math-lab'
import { Route as MdfeRouteImport } from './routes/mdfe'
import { Route as NfceRouteImport } from './routes/nfce'
import { Route as NfeRouteImport } from './routes/nfe'
import { Route as NfseRouteImport } from './routes/nfse'
import { Route as ReformaRouteImport } from './routes/reforma'
import { Route as XmlLabRouteImport } from './routes/xml-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CenariosRoute = CenariosRouteImport.update({
  id: '/cenarios',
  path: '/cenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoRoute = ConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CstatRoute = CstatRouteImport.update({
  id: '/cstat',
  path: '/cstat',
  getParentRoute: () => rootRouteImport,
} as any)
const CteRoute = CteRouteImport.update({
  id: '/cte',
  path: '/cte',
  getParentRoute: () => rootRouteImport,
} as any)
const CteOsRoute = CteOsRouteImport.update({
  id: '/cte-os',
  path: '/cte-os',
  getParentRoute: () => rootRouteImport,
} as any)
const DebuggerRoute = DebuggerRouteImport.update({
  id: '/debugger',
  path: '/debugger',
  getParentRoute: () => rootRouteImport,
} as any)
const MathLabRoute = MathLabRouteImport.update({
  id: '/math-lab',
  path: '/math-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MdfeRoute = MdfeRouteImport.update({
  id: '/mdfe',
  path: '/mdfe',
  getParentRoute: () => rootRouteImport,
} as any)
const NfceRoute = NfceRouteImport.update({
  id: '/nfce',
  path: '/nfce',
  getParentRoute: () => rootRouteImport,
} as any)
const NfeRoute = NfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => rootRouteImport,
} as any)
const NfseRoute = NfseRouteImport.update({
  id: '/nfse',
  path: '/nfse',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformaRoute = ReformaRouteImport.update({
  id: '/reforma',
  path: '/reforma',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlLabRoute = XmlLabRouteImport.update({
  id: '/xml-lab',
  path: '/xml-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cenarios': typeof CenariosRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/cstat': typeof CstatRoute
  '/cte': typeof CteRoute
  '/cte-os': typeof CteOsRoute
  '/debugger': typeof DebuggerRoute
  '/math-lab': typeof MathLabRoute
  '/mdfe': typeof MdfeRoute
  '/nfce': typeof NfceRoute
  '/nfe': typeof NfeRoute
  '/nfse': typeof NfseRoute
  '/reforma': typeof ReformaRoute
  '/xml-lab': typeof XmlLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cenarios': typeof CenariosRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/cstat': typeof CstatRoute
  '/cte': typeof CteRoute
  '/cte-os': typeof CteOsRoute
  '/debugger': typeof DebuggerRoute
  '/math-lab': typeof MathLabRoute
  '/mdfe': typeof MdfeRoute
  '/nfce': typeof NfceRoute
  '/nfe': typeof NfeRoute
  '/nfse': typeof NfseRoute
  '/reforma': typeof ReformaRoute
  '/xml-lab': typeof XmlLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cenarios': typeof CenariosRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/cstat': typeof CstatRoute
  '/cte': typeof CteRoute
  '/cte-os': typeof CteOsRoute
  '/debugger': typeof DebuggerRoute
  '/math-lab': typeof MathLabRoute
  '/mdfe': typeof MdfeRoute
  '/nfce': typeof NfceRoute
  '/nfe': typeof NfeRoute
  '/nfse': typeof NfseRoute
  '/reforma': typeof ReformaRoute
  '/xml-lab': typeof XmlLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cenarios'
    | '/conhecimento'
    | '/cstat'
    | '/cte'
    | '/cte-os'
    | '/debugger'
    | '/math-lab'
    | '/mdfe'
    | '/nfce'
    | '/nfe'
    | '/nfse'
    | '/reforma'
    | '/xml-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cenarios'
    | '/conhecimento'
    | '/cstat'
    | '/cte'
    | '/cte-os'
    | '/debugger'
    | '/math-lab'
    | '/mdfe'
    | '/nfce'
    | '/nfe'
    | '/nfse'
    | '/reforma'
    | '/xml-lab'
  id:
    | '__root__'
    | '/'
    | '/cenarios'
    | '/conhecimento'
    | '/cstat'
    | '/cte'
    | '/cte-os'
    | '/debugger'
    | '/math-lab'
    | '/mdfe'
    | '/nfce'
    | '/nfe'
    | '/nfse'
    | '/reforma'
    | '/xml-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenariosRoute: typeof CenariosRoute
  ConhecimentoRoute: typeof ConhecimentoRoute
  CstatRoute: typeof CstatRoute
  CteRoute: typeof CteRoute
  CteOsRoute: typeof CteOsRoute
  DebuggerRoute: typeof DebuggerRoute
  MathLabRoute: typeof MathLabRoute
  MdfeRoute: typeof MdfeRoute
  NfceRoute: typeof NfceRoute
  NfeRoute: typeof NfeRoute
  NfseRoute: typeof NfseRoute
  ReformaRoute: typeof ReformaRoute
  XmlLabRoute: typeof XmlLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenarios': {
      id: '/cenarios'
      path: '/cenarios'
      fullPath: '/cenarios'
      preLoaderRoute: typeof CenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento': {
      id: '/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof ConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cstat': {
      id: '/cstat'
      path: '/cstat'
      fullPath: '/cstat'
      preLoaderRoute: typeof CstatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cte': {
      id: '/cte'
      path: '/cte'
      fullPath: '/cte'
      preLoaderRoute: typeof CteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cte-os': {
      id: '/cte-os'
      path: '/cte-os'
      fullPath: '/cte-os'
      preLoaderRoute: typeof CteOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debugger': {
      id: '/debugger'
      path: '/debugger'
      fullPath: '/debugger'
      preLoaderRoute: typeof DebuggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math-lab': {
      id: '/math-lab'
      path: '/math-lab'
      fullPath: '/math-lab'
      preLoaderRoute: typeof MathLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdfe': {
      id: '/mdfe'
      path: '/mdfe'
      fullPath: '/mdfe'
      preLoaderRoute: typeof MdfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfce': {
      id: '/nfce'
      path: '/nfce'
      fullPath: '/nfce'
      preLoaderRoute: typeof NfceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfe': {
      id: '/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof NfeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfse': {
      id: '/nfse'
      path: '/nfse'
      fullPath: '/nfse'
      preLoaderRoute: typeof NfseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforma': {
      id: '/reforma'
      path: '/reforma'
      fullPath: '/reforma'
      preLoaderRoute: typeof ReformaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-lab': {
      id: '/xml-lab'
      path: '/xml-lab'
      fullPath: '/xml-lab'
      preLoaderRoute: typeof XmlLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenariosRoute: CenariosRoute,
  ConhecimentoRoute: ConhecimentoRoute,
  CstatRoute: CstatRoute,
  CteRoute: CteRoute,
  CteOsRoute: CteOsRoute,
  DebuggerRoute: DebuggerRoute,
  MathLabRoute: MathLabRoute,
  MdfeRoute: MdfeRoute,
  NfceRoute: NfceRoute,
  NfeRoute: NfeRoute,
  NfseRoute: NfseRoute,
  ReformaRoute: ReformaRoute,
  XmlLabRoute: XmlLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
