import type { DesafioFiscal, TrilhaFiscal } from "./types";

const aula = (
  id: string,
  titulo: string,
  conceito: string,
  exemplo: string,
  simulacao: string,
  exercicio: string,
  erroProposital: string,
  diagnostico: string,
  solucao: string,
  testeFinal: string,
) => ({
  id,
  titulo,
  conceito,
  exemplo,
  simulacao,
  exercicio,
  erroProposital,
  diagnostico,
  solucao,
  testeFinal,
});

export const trilhas: TrilhaFiscal[] = [
  {
    id: "t1",
    numero: 1,
    titulo: "Fundamentos fiscais",
    resumo: "O que é documento fiscal eletrônico, chave de acesso, autorização e evento.",
    aulas: [
      aula(
        "t1.a1",
        "Anatomia de um documento fiscal eletrônico",
        "Um documento fiscal eletrônico é um XML assinado, autorizado antes da operação e identificado por uma chave de 44 posições.",
        "Uma NF-e de venda com emitente, destinatário, itens, impostos e totais.",
        "Abra o Laboratório de XML e percorra os grupos do exemplo.",
        "Localize a chave de acesso dentro do XML de exemplo.",
        "Uma chave com 43 dígitos foi colada no documento.",
        "A validação de tamanho da chave falha antes mesmo da transmissão.",
        "Reimportar o XML de origem em vez de digitar a chave.",
        "Execute o Fiscal Debugger e confirme que a regra de chave passou.",
      ),
      aula(
        "t1.a2",
        "Autorização, rejeição e evento",
        "Autorização é a resposta do fisco ao documento; rejeição indica regra violada; evento é um fato posterior registrado sobre o documento.",
        "Cancelamento e carta de correção são eventos, não novos documentos.",
        "Na Central de Manifestação, registre uma ciência e observe o histórico.",
        "Identifique qual situação exige justificativa.",
        "Manifestação de desconhecimento enviada com justificativa curta.",
        "A regra de justificativa mínima acusa o problema antes do envio.",
        "Escrever uma justificativa objetiva e suficiente.",
        "Repita a manifestação e confira o resultado no histórico.",
      ),
    ],
  },
  {
    id: "t2",
    numero: 2,
    titulo: "NF-e 55",
    resumo: "Operações, participantes, CFOP, tributação por item e totais.",
    documento: "nfe55",
    aulas: [
      aula(
        "t2.a1",
        "Da operação ao CFOP",
        "O CFOP traduz a operação em um código que orienta escrituração e tributação.",
        "Venda interna 5102; venda interestadual 6102.",
        "No módulo NF-e, troque a UF do destinatário e observe a sugestão de CFOP.",
        "Escolha a operação de devolução e veja o que passa a ser exigido.",
        "Venda para outro estado mantida com CFOP 5102.",
        "A regra de coerência entre CFOP e UF de destino falha.",
        "Ajustar a operação e deixar o CFOP ser derivado da tabela.",
        "Rode o debugger e confirme a regra atendida.",
      ),
    ],
  },
  {
    id: "t3",
    numero: 3,
    titulo: "NFC-e 65",
    resumo: "Varejo, consumidor final, pagamento, QR Code e contingência.",
    documento: "nfce65",
    aulas: [
      aula(
        "t3.a1",
        "O caixa e a contingência",
        "Quando o serviço não responde, o caixa não pode parar: o documento entra em fila conforme a regra da UF.",
        "Venda finalizada sem comunicação, transmitida minutos depois.",
        "No módulo NFC-e, desligue a conexão simulada e finalize uma venda.",
        "Verifique o que fica pendente na fila.",
        "Cupom finalizado com pagamento menor que o total.",
        "A regra de soma dos pagamentos acusa saldo em aberto.",
        "Registrar o pagamento faltante antes de transmitir.",
        "Reenvie a fila com a conexão religada.",
      ),
    ],
  },
  {
    id: "t4",
    numero: 4,
    titulo: "NFS-e",
    resumo: "Serviço, município, item da lista, ISS e retenções.",
    documento: "nfse",
    aulas: [
      aula(
        "t4.a1",
        "Por que NFS-e é diferente",
        "O ISS é municipal: o leiaute, o código do serviço e a alíquota dependem da prefeitura.",
        "O mesmo serviço pode ter código diferente em dois municípios.",
        "No módulo NFS-e, preencha os quatro campos essenciais e abra a tributação avançada.",
        "Identifique o que muda quando o ISS é retido pelo tomador.",
        "Discriminação preenchida com 'serviços prestados'.",
        "A regra de discriminação suficiente gera alerta.",
        "Detalhar o serviço conforme o contrato.",
        "Reemita e confirme o alerta resolvido.",
      ),
    ],
  },
  {
    id: "t5",
    numero: 5,
    titulo: "CT-e 57",
    resumo: "Participantes, tomador, documentos vinculados e composição do frete.",
    documento: "cte57",
    aulas: [
      aula(
        "t5.a1",
        "Quem é o tomador",
        "O tomador é quem contrata e paga o frete; define crédito, cobrança e escrituração.",
        "Frete CIF costuma ter o remetente como tomador; FOB, o destinatário.",
        "No módulo CT-e, importe um XML de NF-e e escolha o tomador.",
        "Troque o tomador e observe o impacto conceitual.",
        "Tomador informado fora da lista de participantes.",
        "A regra de tomador válido falha.",
        "Selecionar um participante já informado no documento.",
        "Rode o debugger para o CT-e.",
      ),
    ],
  },
  {
    id: "t6",
    numero: 6,
    titulo: "CT-e OS 67",
    resumo: "Pessoas, valores, excesso de bagagem e diferenças em relação ao CT-e.",
    documento: "cteos67",
    aulas: [
      aula(
        "t6.a1",
        "Quando o transporte não tem carga",
        "Transporte de pessoas e de valores usa leiaute próprio, sem documentos de carga vinculados.",
        "Fretamento de ônibus e transporte de malotes.",
        "No módulo CT-e OS, alterne entre as abas de pessoas e valores.",
        "Observe quais grupos deixam de existir em relação ao CT-e.",
        "Tentativa de vincular NF-e à prestação.",
        "O alerta de modalidade indica leiaute incorreto.",
        "Usar CT-e 57 quando houver carga documentada.",
        "Confira a modalidade escolhida no painel técnico.",
      ),
    ],
  },
  {
    id: "t7",
    numero: 7,
    titulo: "MDF-e 58",
    resumo: "Viagem, veículo, condutor, percurso e encerramento.",
    documento: "mdfe58",
    aulas: [
      aula(
        "t7.a1",
        "A viagem como unidade",
        "O manifesto agrupa os documentos de uma viagem e precisa ser encerrado ao fim dela.",
        "Três CT-e da mesma rota reunidos em um manifesto.",
        "No módulo MDF-e, selecione documentos e monte o percurso.",
        "Identifique o que acontece se o motorista mudar no meio da viagem.",
        "CPF do condutor inválido.",
        "A regra de CPF acusa antes da transmissão.",
        "Corrigir o cadastro do motorista.",
        "Rode o debugger para o MDF-e.",
      ),
    ],
  },
  {
    id: "t8",
    numero: 8,
    titulo: "XML",
    resumo: "Grupos, tags, leitura, comparação e diagnóstico pelo arquivo.",
    aulas: [
      aula(
        "t8.a1",
        "Ler o XML como um mapa",
        "Cada grupo do XML corresponde a uma parte do documento: identificação, participantes, itens, impostos, totais.",
        "O grupo de ICMS muda conforme a situação tributária do item.",
        "No Laboratório de XML, selecione uma tag e veja o campo correspondente.",
        "Compare o XML correto com o incorreto e aponte a diferença.",
        "Valor de imposto divergente da base.",
        "A comparação destaca a linha divergente.",
        "Recalcular o imposto no back-end.",
        "Rode o debugger e confirme.",
      ),
    ],
  },
  {
    id: "t9",
    numero: 9,
    titulo: "Cálculos fiscais",
    resumo: "Base, reduções, ICMS, ST, FCP, DIFAL, IPI e contribuições.",
    aulas: [
      aula(
        "t9.a1",
        "A base vem antes do imposto",
        "Quase todo erro de cálculo começa na composição da base, não na alíquota.",
        "Frete e desconto mudam a base e, com ela, todos os tributos do item.",
        "No Laboratório de Cálculos, altere frete e desconto e observe o resultado.",
        "Reproduza o mesmo valor em dois caminhos diferentes.",
        "Arredondamento aplicado em etapa errada.",
        "O resultado diverge por centavos.",
        "Arredondar apenas no valor final, com duas casas.",
        "Compare com o valor esperado pela regra de cálculo.",
      ),
    ],
  },
  {
    id: "t10",
    numero: 10,
    titulo: "Rejeições e CStats",
    resumo: "Diagnóstico estruturado: causa, regra, campo, XML e correção.",
    aulas: [
      aula(
        "t10.a1",
        "Diagnosticar em vez de adivinhar",
        "Toda rejeição aponta para uma regra, que aponta para um campo, que aparece no XML.",
        "Divergência de cálculo sempre leva a base, alíquota ou arredondamento.",
        "Na Central de Diagnóstico, pesquise por campo e siga a cadeia.",
        "Monte o checklist de suporte para uma família de rejeição.",
        "Correção feita no documento sem corrigir o cadastro.",
        "O erro volta na próxima emissão.",
        "Corrigir a origem do dado, não só o documento.",
        "Execute o desafio correspondente.",
      ),
    ],
  },
  {
    id: "t11",
    numero: 11,
    titulo: "Integração com o fisco e provedores",
    resumo: "Responsabilidades do back-end, certificados, ambientes e reenvio.",
    aulas: [
      aula(
        "t11.a1",
        "O que nunca fica no front-end",
        "Certificado, senha, CSC e token ficam no back-end. O front coleta dados e mostra resultado.",
        "Assinatura e transmissão sempre no servidor.",
        "Abra o Mapa de Integração e veja a divisão de responsabilidades.",
        "Liste o que o back-end precisa persistir de cada transmissão.",
        "Token exposto em configuração de front-end.",
        "Qualquer usuário do navegador consegue lê-lo.",
        "Mover o segredo para o back-end.",
        "Revise o painel técnico dos elementos de transmissão.",
      ),
    ],
  },
  {
    id: "t12",
    numero: 12,
    titulo: "Reforma Tributária",
    resumo: "IBS, CBS e IS: conceito, transição e impactos no ERP.",
    aulas: [
      aula(
        "t12.a1",
        "Modelo atual × modelo da reforma",
        "A reforma substitui tributos sobre consumo por IBS e CBS, com imposto seletivo em casos específicos.",
        "Um mesmo item terá tributação no modelo atual e no novo durante a transição.",
        "Abra a área de Reforma Tributária e compare os modelos.",
        "Liste o que muda no cadastro de produtos.",
        "Tratar cronograma como imutável.",
        "Regras e datas ainda estão em evolução.",
        "Versionar tudo por vigência e fonte.",
        "Confira o status de validação de cada item da área.",
      ),
    ],
  },
];

export const desafios: DesafioFiscal[] = [
  {
    id: "d1",
    titulo: "A NF-e foi rejeitada. Descubra o motivo.",
    enunciado:
      "Venda de SP para MG, comprador pessoa física. O documento foi recusado. Analise o XML, identifique o campo, a regra e a família de rejeição.",
    cenarioId: "cen.interestadual-consumidor",
    xml: `<det nItem="1">
  <prod><NCM>73269090</NCM><CFOP>5102</CFOP><vProd>2500.00</vProd></prod>
  <imposto>
    <ICMS><ICMS00><CST>00</CST><vBC>2400.00</vBC><pICMS>12.00</pICMS><vICMS>288.00</vICMS></ICMS00></ICMS>
  </imposto>
</det>`,
    campoCorreto: "nfe.cfop",
    regraCorreta: "REGRA-CFOP-DESTINO",
    cstatCorreto: "cstat.pendente.cfop",
    explicacao:
      "A operação cruza estados, então o CFOP deveria ser da série 6. Além disso, falta o grupo de partilha para a UF de destino.",
    correcao: "Derivar o CFOP pela UF de destino e calcular a partilha devida ao destino.",
  },
  {
    id: "d2",
    titulo: "O imposto não bate. Onde está o erro?",
    enunciado:
      "A base é 2.400,00 e a alíquota é 12%, mas o XML traz 290,00 de ICMS. Identifique o campo, a regra e a correção.",
    xml: `<ICMS00><vBC>2400.00</vBC><pICMS>12.00</pICMS><vICMS>290.00</vICMS></ICMS00>`,
    campoCorreto: "nfe.vbc",
    regraCorreta: "REGRA-ICMS-VALOR",
    cstatCorreto: "cstat.pendente.calculo",
    explicacao: "2.400,00 × 12% = 288,00. O valor informado diverge em 2,00.",
    correcao: "Recalcular no back-end e proibir campo de imposto editável.",
  },
  {
    id: "d3",
    titulo: "O manifesto não foi aceito.",
    enunciado: "O MDF-e foi recusado logo na validação do condutor. Descubra o campo e a regra.",
    xml: `<condutor><xNome>João da Silva</xNome><CPF>11111111111</CPF></condutor>`,
    campoCorreto: "mdfe.condutor",
    regraCorreta: "REGRA-MDFE-CONDUTOR",
    cstatCorreto: "cstat.pendente.mdfe",
    explicacao: "CPF com todos os dígitos iguais não passa na verificação dos dígitos verificadores.",
    correcao: "Corrigir o CPF no cadastro do motorista e validar no cadastro, não na emissão.",
  },
  {
    id: "d4",
    titulo: "A venda no caixa não fecha.",
    enunciado:
      "NFC-e de 150,00 recusada. Os pagamentos somam menos que o total. Encontre campo, regra e família de rejeição.",
    xml: `<total><ICMSTot><vNF>150.00</vNF></ICMSTot></total>
<pag>
  <detPag><tPag>01</tPag><vPag>100.00</vPag></detPag>
  <detPag><tPag>03</tPag><vPag>30.00</vPag></detPag>
</pag>`,
    campoCorreto: "nfce.pag",
    regraCorreta: "REGRA-PAG-SOMA",
    cstatCorreto: "cstat.pendente.pagamento",
    explicacao: "100,00 + 30,00 = 130,00, abaixo dos 150,00 do documento (exemplo didático).",
    correcao: "Bloquear o fechamento do caixa enquanto a soma dos pagamentos for menor que o total.",
  },
  {
    id: "d5",
    titulo: "Quem paga o frete?",
    enunciado:
      "CT-e recusado: o tomador do serviço não foi identificado. Descubra o campo e a regra.",
    xml: `<ide><toma3><toma></toma></toma3></ide>
<rem><xNome>Aurora Distribuidora (fictício)</xNome></rem>
<dest><xNome>Cliente Exemplo (fictício)</xNome></dest>`,
    campoCorreto: "cte.tomador",
    regraCorreta: "REGRA-CTE-TOMADOR",
    cstatCorreto: "cstat.pendente.cte",
    explicacao: "O indicador de tomador está vazio; o ERP precisa saber quem paga pela prestação.",
    correcao: "Tornar o tomador obrigatório na tela e derivá-lo do tipo de frete quando possível.",
  },
  {
    id: "d6",
    titulo: "A nota de serviço voltou.",
    enunciado:
      "NFS-e recusada com descrição de serviço muito curta. Identifique o campo e a regra.",
    xml: `<Servico><Discriminacao>Serv.</Discriminacao><Valores><ValorServicos>800.00</ValorServicos></Valores></Servico>`,
    campoCorreto: "nfse.servico",
    regraCorreta: "REGRA-NFSE-DESCRICAO",
    cstatCorreto: "cstat.pendente.nfse",
    explicacao:
      "A descrição não identifica o serviço prestado. O limite mínimo usado aqui é ilustrativo; cada município pode ter regra própria.",
    correcao: "Exigir descrição mínima na tela e parametrizar o limite por município.",
  },
];
