import type { CampoFiscal, Procedencia } from "./types";

const pend = (fonteId: string, documento: string): Procedencia => ({
  status: "pendente",
  fonteId,
  documento,
  vigencia: { observacao: "Vigência e versão de leiaute não registradas neste ambiente." },
});

export const campos: CampoFiscal[] = [
  {
    id: "nfe.cfop",
    documento: "nfe55",
    grupoXml: "prod",
    tagXml: "CFOP",
    nome: "Código Fiscal de Operações e Prestações",
    tipo: "Numérico, 4 posições",
    obrigatoriedade: "Obrigatório por item",
    conceito:
      "Classifica a natureza da operação: o que está sendo feito, para onde vai e se há circulação com ou sem transferência de propriedade.",
    porQueExiste:
      "É a chave que liga a operação à escrituração fiscal e às regras de tributação e crédito.",
    quemInforma: "O ERP, a partir da operação escolhida e do cadastro do destinatário.",
    origemDado: "Tabela de operações × destino (interno/interestadual) × tipo de destinatário.",
    dependeDe: ["UF do emitente", "UF do destinatário", "Tipo de operação", "Finalidade"],
    influencia: ["CST/CSOSN", "Cálculo de ICMS", "Necessidade de DIFAL", "Escrituração"],
    exemploXml: "<prod><CFOP>6102</CFOP></prod>",
    regras: ["REGRA-CFOP-DESTINO", "REGRA-CFOP-DEVOLUCAO"],
    cstats: ["cstat.pendente.cfop"],
    implementacaoErp: [
      "Nunca deixar o operador digitar CFOP livre sem validação.",
      "Derivar o CFOP de uma tabela versionada de operações no back-end.",
      "Registrar qual regra gerou o código sugerido para auditoria.",
    ],
    testes: ["Venda interna", "Venda interestadual", "Devolução de compra"],
    procedencia: pend("moc-nfe", "NF-e"),
    docId: "m2.cfop",
  },
  {
    id: "nfe.vbc",
    documento: "nfe55",
    grupoXml: "imposto/ICMS",
    tagXml: "vBC",
    nome: "Base de cálculo do ICMS",
    tipo: "Decimal, 2 casas",
    obrigatoriedade: "Obrigatório quando há ICMS a destacar",
    conceito: "Valor sobre o qual a alíquota de ICMS é aplicada.",
    porQueExiste: "Separa o valor tributável do valor comercial do item.",
    quemInforma: "Calculado pelo sistema, nunca digitado.",
    origemDado: "Valor do produto, descontos, frete, seguro, despesas e redução aplicável.",
    dependeDe: ["vProd", "vDesc", "vFrete", "vSeg", "vOutro", "Redução de base"],
    influencia: ["vICMS", "vBCST", "Totais da nota"],
    calculoId: "calc.base",
    exemploXml: "<ICMS00><vBC>2400.00</vBC><pICMS>12.00</pICMS><vICMS>288.00</vICMS></ICMS00>",
    regras: ["REGRA-ICMS-VALOR", "REGRA-TOTAL-ITENS"],
    cstats: ["cstat.pendente.calculo"],
    implementacaoErp: [
      "Centralizar o cálculo no back-end; o front apenas exibe prévia.",
      "Persistir os componentes da base, não só o resultado.",
    ],
    testes: ["Item com desconto", "Item com frete rateado", "Item com redução de base"],
    procedencia: pend("moc-nfe", "NF-e"),
    docId: "m2.previa",
  },
  {
    id: "nfe.cst",
    documento: "nfe55",
    grupoXml: "imposto/ICMS",
    tagXml: "CST / CSOSN",
    nome: "Código de situação tributária do ICMS",
    tipo: "Numérico",
    obrigatoriedade: "Obrigatório por item",
    conceito:
      "Indica como o item é tratado no ICMS: tributado, isento, com substituição, diferido, suspenso, entre outros.",
    porQueExiste: "Determina quais grupos XML de ICMS podem ou devem ser preenchidos.",
    quemInforma: "ERP, a partir do regime do emitente e da tributação do produto por UF.",
    origemDado: "Cadastro fiscal do produto × regime tributário × UF de destino.",
    dependeDe: ["Regime tributário", "NCM", "UF de destino", "Tipo de operação"],
    influencia: ["Grupo XML de ICMS", "Obrigatoriedade de vBC e pICMS", "ST e FCP"],
    exemploXml: "<ICMS><ICMS00><orig>0</orig><CST>00</CST></ICMS00></ICMS>",
    regras: ["REGRA-CST-GRUPO", "REGRA-CSOSN-REGIME"],
    cstats: ["cstat.pendente.cst"],
    implementacaoErp: [
      "Simples Nacional usa CSOSN; Regime Normal usa CST. Não misturar.",
      "Manter a tributação por produto e por UF, versionada.",
    ],
    testes: ["Regime normal tributado", "Simples Nacional", "Item com ST"],
    procedencia: pend("moc-nfe", "NF-e"),
  },
  {
    id: "nfe.ncm",
    documento: "nfe55",
    grupoXml: "prod",
    tagXml: "NCM",
    nome: "Nomenclatura Comum do Mercosul",
    tipo: "Numérico, 8 posições",
    obrigatoriedade: "Obrigatório por item",
    conceito: "Classificação fiscal da mercadoria.",
    porQueExiste: "Define IPI, ST, benefícios e controles aduaneiros aplicáveis ao produto.",
    quemInforma: "Cadastro de produtos.",
    origemDado: "Cadastro do produto, mantido pelo fiscal da empresa.",
    dependeDe: ["Cadastro do produto"],
    influencia: ["IPI", "ICMS-ST", "Benefícios fiscais", "Reforma: classificação"],
    exemploXml: "<prod><NCM>73269090</NCM></prod>",
    regras: ["REGRA-NCM-FORMATO"],
    cstats: ["cstat.pendente.ncm"],
    implementacaoErp: [
      "Validar o formato antes de transmitir.",
      "Bloquear cadastro de produto sem NCM.",
    ],
    testes: ["NCM com 8 dígitos", "NCM ausente", "NCM com letras"],
    procedencia: pend("moc-nfe", "NF-e"),
    docId: "m2.itens",
  },
  {
    id: "nfe.difal",
    documento: "nfe55",
    grupoXml: "imposto/ICMSUFDest",
    tagXml: "vICMSUFDest",
    nome: "ICMS devido à UF de destino (DIFAL)",
    tipo: "Decimal, 2 casas",
    obrigatoriedade: "Condicional — operação interestadual a consumidor final",
    conceito: "Parcela do ICMS que cabe ao estado de destino na venda a consumidor final.",
    porQueExiste: "Reparte a arrecadação entre origem e destino no comércio interestadual.",
    quemInforma: "Calculado pelo sistema.",
    origemDado: "Alíquota interna do destino e alíquota interestadual da operação.",
    dependeDe: ["UF origem", "UF destino", "Consumidor final", "Base"],
    influencia: ["Totais", "Obrigações acessórias no destino"],
    calculoId: "calc.difal",
    exemploXml: "<ICMSUFDest><vBCUFDest>2400.00</vBCUFDest><vICMSUFDest>144.00</vICMSUFDest></ICMSUFDest>",
    regras: ["REGRA-DIFAL-OBRIGATORIO"],
    cstats: ["cstat.pendente.difal"],
    implementacaoErp: [
      "Detectar automaticamente a condição de consumidor final não contribuinte.",
      "Manter tabela de alíquotas internas por UF, versionada e datada.",
    ],
    testes: ["Interestadual a não contribuinte", "Interestadual a contribuinte"],
    procedencia: pend("moc-nfe", "NF-e"),
  },
  {
    id: "nfce.pag",
    documento: "nfce65",
    grupoXml: "pag",
    tagXml: "detPag / vTroco",
    nome: "Formas de pagamento e troco",
    tipo: "Grupo repetível",
    obrigatoriedade: "Obrigatório",
    conceito: "Registra como a venda foi paga e quanto foi devolvido em troco.",
    porQueExiste: "O documento de consumidor precisa refletir a liquidação da venda no caixa.",
    quemInforma: "PDV.",
    origemDado: "Meios de pagamento configurados no caixa.",
    dependeDe: ["Total da venda"],
    influencia: ["Validação de soma dos pagamentos", "Troco"],
    exemploXml: "<pag><detPag><tPag>01</tPag><vPag>100.00</vPag></detPag><vTroco>5.00</vTroco></pag>",
    regras: ["REGRA-PAG-SOMA"],
    cstats: ["cstat.pendente.pagamento"],
    implementacaoErp: [
      "Somar pagamentos e comparar com o total antes de gerar o XML.",
      "Códigos de meio de pagamento devem vir de tabela oficial — ainda não registrada aqui.",
    ],
    testes: ["Pagamento exato", "Pagamento com troco", "Soma menor que o total"],
    procedencia: pend("mo-nfce", "NFC-e"),
    docId: "m3.pagamento",
  },
  {
    id: "nfce.qrcode",
    documento: "nfce65",
    grupoXml: "infNFeSupl",
    tagXml: "qrCode",
    nome: "QR Code da NFC-e",
    tipo: "String",
    obrigatoriedade: "Obrigatório",
    conceito: "Permite ao consumidor consultar o documento no portal da UF.",
    porQueExiste: "Dá transparência e validação imediata ao consumidor final.",
    quemInforma: "Gerado pelo emissor conforme o algoritmo da UF.",
    origemDado: "Chave, ambiente, identificador e assinatura do CSC.",
    dependeDe: ["Chave de acesso", "CSC da UF"],
    influencia: ["DANFE NFC-e"],
    exemploXml: "<infNFeSupl><qrCode>…</qrCode><urlChave>…</urlChave></infNFeSupl>",
    regras: [],
    cstats: ["cstat.pendente.qrcode"],
    implementacaoErp: [
      "CSC é segredo: fica no back-end, nunca no front nem no PDV em texto claro.",
      "O algoritmo varia por versão do leiaute — confirmar antes de implementar.",
    ],
    testes: ["Emissão em linha", "Emissão em contingência"],
    procedencia: pend("mo-nfce", "NFC-e"),
  },
  {
    id: "nfse.servico",
    documento: "nfse",
    grupoXml: "servico",
    tagXml: "itemListaServico / cTribMunicipio",
    nome: "Item da lista e código municipal do serviço",
    tipo: "Código",
    obrigatoriedade: "Obrigatório",
    conceito: "Classifica o serviço prestado segundo a lista de serviços e o código do município.",
    porQueExiste: "Define alíquota, local de incidência e regras de retenção.",
    quemInforma: "Cadastro de serviços da empresa, por município.",
    origemDado: "Tabela municipal do serviço — varia por prefeitura.",
    dependeDe: ["Município de incidência"],
    influencia: ["Alíquota de ISS", "Retenção", "Obrigatoriedade de campos municipais"],
    calculoId: "calc.iss",
    exemploXml: "<servico><itemListaServico>…</itemListaServico><discriminacao>…</discriminacao></servico>",
    regras: ["REGRA-NFSE-DESCRICAO"],
    cstats: ["cstat.pendente.nfse"],
    implementacaoErp: [
      "Manter o código de serviço por município, não global.",
      "Tratar o padrão nacional e o padrão municipal como leiautes distintos.",
    ],
    testes: ["Serviço no município do prestador", "Serviço em outro município", "ISS retido"],
    procedencia: pend("nfse-nacional", "NFS-e"),
    docId: "m4.servico",
  },
  {
    id: "cte.tomador",
    documento: "cte57",
    grupoXml: "ide/toma",
    tagXml: "toma3 / toma4",
    nome: "Tomador do serviço de transporte",
    tipo: "Enumeração + dados do participante",
    obrigatoriedade: "Obrigatório",
    conceito: "Indica quem contratou e paga o frete.",
    porQueExiste: "Define quem toma crédito, quem é cobrado e como o documento é escriturado.",
    quemInforma: "Ordem de coleta / contrato de transporte.",
    origemDado: "Cadastro do cliente e condição de frete (CIF/FOB).",
    dependeDe: ["Remetente", "Destinatário", "Expedidor", "Recebedor"],
    influencia: ["Escrituração", "ICMS da prestação", "Cobrança"],
    exemploXml: "<ide><toma3><toma>0</toma></toma3></ide>",
    regras: ["REGRA-CTE-TOMADOR"],
    cstats: ["cstat.pendente.cte"],
    implementacaoErp: [
      "Derivar o tomador da condição de frete registrada no pedido.",
      "Impedir tomador que não seja um dos participantes informados.",
    ],
    testes: ["Tomador remetente", "Tomador destinatário", "Tomador terceiro"],
    procedencia: pend("mo-cte", "CT-e"),
    docId: "m5.partes",
  },
  {
    id: "cte.docs",
    documento: "cte57",
    grupoXml: "infCTeNorm/infDoc",
    tagXml: "infNFe/chave",
    nome: "NF-e vinculadas à prestação",
    tipo: "Lista de chaves de 44 posições",
    obrigatoriedade: "Obrigatório quando há documentos de carga",
    conceito: "Liga a carga transportada ao serviço de transporte.",
    porQueExiste: "Permite rastrear o que está sendo transportado e conferir valores e pesos.",
    quemInforma: "Importação dos XML das notas ou integração com o embarque.",
    origemDado: "XML das NF-e do embarque.",
    dependeDe: ["Chave de acesso válida"],
    influencia: ["Valor da carga", "Peso", "MDF-e"],
    exemploXml: "<infNFe><chave>3525…</chave></infNFe>",
    regras: ["REGRA-CHAVE-44"],
    cstats: ["cstat.pendente.chave"],
    implementacaoErp: [
      "Validar tamanho e dígito verificador da chave antes de transmitir.",
      "Guardar o XML de origem, não apenas a chave.",
    ],
    testes: ["Chave válida", "Chave com 43 dígitos", "Arquivo sem chave reconhecível"],
    procedencia: pend("mo-cte", "CT-e"),
    docId: "m5.xml",
  },
  {
    id: "cteos.modalidade",
    documento: "cteos67",
    grupoXml: "ide",
    tagXml: "tpServ",
    nome: "Tipo de serviço do CT-e OS",
    tipo: "Enumeração",
    obrigatoriedade: "Obrigatório",
    conceito: "Distingue transporte de pessoas, de valores e excesso de bagagem.",
    porQueExiste: "Cada modalidade exige grupos diferentes no leiaute.",
    quemInforma: "Operação contratada.",
    origemDado: "Contrato de prestação.",
    dependeDe: [],
    influencia: ["Grupos obrigatórios", "Validações", "Tributação"],
    exemploXml: "<ide><tpServ>…</tpServ></ide>",
    regras: ["REGRA-CTEOS-MODALIDADE"],
    cstats: ["cstat.pendente.cteos"],
    implementacaoErp: [
      "Selecionar a modalidade antes de habilitar os demais grupos da tela.",
      "Códigos de tpServ devem vir do manual vigente — não fixados aqui.",
    ],
    testes: ["Transporte de pessoas", "Transporte de valores"],
    procedencia: pend("mo-cte", "CT-e OS"),
    docId: "m6.modalidade",
  },
  {
    id: "mdfe.condutor",
    documento: "mdfe58",
    grupoXml: "infModal/rodo/veicTracao/condutor",
    tagXml: "condutor/CPF",
    nome: "Condutor do veículo",
    tipo: "Nome + CPF",
    obrigatoriedade: "Obrigatório no modal rodoviário",
    conceito: "Identifica quem conduz o veículo na viagem manifestada.",
    porQueExiste: "Permite fiscalização em trânsito e responsabilização pela viagem.",
    quemInforma: "Cadastro de motoristas.",
    origemDado: "Cadastro de pessoal do transportador.",
    dependeDe: ["Veículo de tração"],
    influencia: ["Evento de inclusão de condutor", "Fiscalização em trânsito"],
    exemploXml: "<condutor><xNome>…</xNome><CPF>…</CPF></condutor>",
    regras: ["REGRA-MDFE-CONDUTOR"],
    cstats: ["cstat.pendente.mdfe"],
    implementacaoErp: [
      "Validar CPF antes de transmitir.",
      "Permitir troca de condutor por evento, sem reemitir o manifesto.",
    ],
    testes: ["Condutor informado", "CPF inválido", "Troca de motorista na viagem"],
    procedencia: pend("mo-mdfe", "MDF-e"),
    docId: "m7.condutor",
  },
  {
    id: "mdfe.percurso",
    documento: "mdfe58",
    grupoXml: "ide",
    tagXml: "UFIni / UFFim / infPercurso",
    nome: "Percurso da viagem",
    tipo: "Siglas de UF",
    obrigatoriedade: "Obrigatório",
    conceito: "UF de início, UF de fim e as unidades federadas percorridas.",
    porQueExiste: "Define quais fiscos acompanham a viagem.",
    quemInforma: "Roteirização da viagem.",
    origemDado: "Rota planejada do embarque.",
    dependeDe: ["Documentos vinculados"],
    influencia: ["Validação de coerência com os documentos", "Encerramento"],
    exemploXml: "<ide><UFIni>SP</UFIni><UFFim>MG</UFFim></ide>",
    regras: ["REGRA-MDFE-PERCURSO"],
    cstats: ["cstat.pendente.mdfe"],
    implementacaoErp: [
      "Sugerir o percurso a partir das UFs dos documentos vinculados.",
      "Alertar quando a UF final não coincidir com o destino dos documentos.",
    ],
    testes: ["Viagem interna", "Viagem interestadual com percurso intermediário"],
    procedencia: pend("mo-mdfe", "MDF-e"),
    docId: "m7.percurso",
  },
  {
    id: "evento.manifestacao",
    documento: "eventos",
    grupoXml: "evento/detEvento",
    tagXml: "descEvento / xJust",
    nome: "Evento de manifestação do destinatário",
    tipo: "Tipo de evento + justificativa condicional",
    obrigatoriedade: "Condicional",
    conceito:
      "Registra ciência, confirmação, desconhecimento ou operação não realizada sobre uma NF-e recebida.",
    porQueExiste: "Formaliza a posição do destinatário e produz efeitos sobre a operação.",
    quemInforma: "Destinatário, pelo ERP.",
    origemDado: "Conferência do recebimento contra o pedido de compra.",
    dependeDe: ["Chave de acesso", "Situação atual da manifestação"],
    influencia: ["Acesso ao XML", "Escrituração", "Relacionamento com o emitente"],
    exemploXml: "<detEvento><descEvento>…</descEvento><xJust>…</xJust></detEvento>",
    regras: ["REGRA-MANIF-JUSTIFICATIVA", "REGRA-MANIF-DUPLICIDADE"],
    cstats: ["cstat.pendente.evento"],
    implementacaoErp: [
      "Exigir justificativa nos tipos que a requerem, com tamanho mínimo.",
      "Impedir reenvio do mesmo evento sem aviso; tratar duplicidade pelo retorno do fisco.",
    ],
    testes: ["Ciência", "Desconhecimento sem justificativa", "Repetição do mesmo evento"],
    procedencia: pend("moc-nfe", "Eventos"),
    docId: "m1.manifestar",
  },
];

export const campoById = new Map(campos.map((c) => [c.id, c]));
export const camposPorDocumento = (doc: string) => campos.filter((c) => c.documento === doc);
export const campoPorDocId = new Map(
  campos.filter((c) => c.docId).map((c) => [c.docId as string, c]),
);
