import type { CenarioFiscal, Procedencia } from "./types";

const didatico: Procedencia = {
  status: "ilustrativo",
  fonteId: "sem-fonte",
  vigencia: { observacao: "Cenário didático deste ambiente." },
};

export const cenarios: CenarioFiscal[] = [
  {
    id: "cen.interestadual-consumidor",
    nome: "Venda interestadual para consumidor final não contribuinte",
    objetivo: "Entender a partilha do ICMS entre origem e destino.",
    documento: "nfe55",
    participantes: "Emitente em SP, pessoa física em MG",
    operacao: "Venda de mercadoria",
    regime: "Regime Normal",
    origem: "SP",
    destino: "MG",
    consumidor: "Consumidor final não contribuinte",
    tributacao: ["ICMS interestadual", "DIFAL", "PIS", "COFINS"],
    passos: [
      "Cadastro: cliente pessoa física, sem inscrição estadual, indicador de não contribuinte",
      "Operação: venda de mercadoria para fora do estado",
      "CFOP da série 6, por ser interestadual",
      "Tributação: alíquota interestadual na origem",
      "Cálculo: diferença entre a alíquota interna do destino e a interestadual",
      "XML: preencher o grupo de partilha para a UF de destino",
      "Validação: partilha obrigatória nesta combinação",
      "Autorização e guarda do protocolo",
      "Erros possíveis: cadastro do cliente como contribuinte, ausência do grupo de partilha",
    ],
    campos: ["nfe.cfop", "nfe.difal", "nfe.vbc"],
    xml: `<det nItem="1">
  <prod><cProd>P-001</cProd><NCM>73269090</NCM><CFOP>6102</CFOP><vProd>2500.00</vProd></prod>
  <imposto>
    <ICMS><ICMS00><orig>0</orig><CST>00</CST><vBC>2400.00</vBC><pICMS>12.00</pICMS><vICMS>288.00</vICMS></ICMS00></ICMS>
    <ICMSUFDest><vBCUFDest>2400.00</vBCUFDest><pICMSUFDest>18.00</pICMSUFDest><pICMSInter>12.00</pICMSInter><vICMSUFDest>144.00</vICMSUFDest></ICMSUFDest>
  </imposto>
</det>`,
    validacoes: ["REGRA-CFOP-DESTINO", "REGRA-DIFAL-OBRIGATORIO", "REGRA-ICMS-VALOR"],
    possiveisRejeicoes: ["cstat.pendente.difal", "cstat.pendente.cfop"],
    solucao: "Corrigir o indicador de contribuinte e recalcular a partilha antes de retransmitir.",
    procedencia: didatico,
  },
  {
    id: "cen.devolucao",
    nome: "Devolução de compra",
    objetivo: "Ligar a devolução à nota de origem.",
    documento: "nfe55",
    participantes: "Comprador devolvendo ao fornecedor",
    operacao: "Devolução",
    regime: "Regime Normal",
    origem: "SP",
    destino: "SP",
    consumidor: "Contribuinte",
    tributacao: ["Espelho da tributação da nota original"],
    passos: [
      "Localizar a nota original recebida",
      "Gerar a devolução a partir dela, não em branco",
      "CFOP de devolução conforme a operação original",
      "Referenciar a chave da nota devolvida",
      "Espelhar base, alíquotas e valores da origem",
      "Validar e transmitir",
    ],
    campos: ["nfe.cfop", "nfe.vbc"],
    xml: `<NFref><refNFe>35250400011122000199550010000001231000001230</refNFe></NFref>`,
    validacoes: ["REGRA-CFOP-DEVOLUCAO", "REGRA-TOTAL-ITENS"],
    possiveisRejeicoes: ["cstat.pendente.referencia"],
    solucao: "Informar a chave da nota original e espelhar a tributação.",
    procedencia: didatico,
  },
  {
    id: "cen.nfce-contingencia",
    nome: "Venda no PDV com queda de comunicação",
    objetivo: "Entender o comportamento do caixa quando o serviço não responde.",
    documento: "nfce65",
    participantes: "Varejista e consumidor presencial",
    operacao: "Venda a consumidor final",
    regime: "Regime Normal",
    origem: "SP",
    destino: "SP",
    consumidor: "Consumidor final",
    tributacao: ["ICMS", "PIS", "COFINS"],
    passos: [
      "Registro dos itens e dos pagamentos",
      "Tentativa de autorização",
      "Falha de comunicação com o serviço",
      "Entrada em contingência conforme a regra da UF",
      "Guarda do documento em fila local",
      "Transmissão posterior quando o serviço voltar",
    ],
    campos: ["nfce.pag", "nfce.qrcode"],
    xml: `<ide><tpEmis><!-- modalidade de emissão depende da UF --></tpEmis></ide>`,
    validacoes: ["REGRA-PAG-SOMA"],
    possiveisRejeicoes: ["cstat.pendente.pagamento", "cstat.pendente.qrcode"],
    solucao:
      "Manter a fila local e retransmitir; modalidades e prazos de contingência dependem da UF e não são fixados aqui.",
    procedencia: didatico,
  },
  {
    id: "cen.cte-mdfe",
    nome: "Carga com CT-e e manifesto de viagem",
    objetivo: "Ver a cadeia NF-e → CT-e → MDF-e funcionando.",
    documento: "cte57",
    participantes: "Remetente, transportador, destinatário e tomador",
    operacao: "Prestação de serviço de transporte",
    regime: "Regime Normal",
    origem: "SP",
    destino: "MG",
    consumidor: "Contribuinte",
    tributacao: ["ICMS da prestação"],
    passos: [
      "Importar as NF-e da carga",
      "Definir o tomador conforme a condição de frete",
      "Compor o frete e tributar a prestação",
      "Autorizar o CT-e",
      "Reunir os CT-e da viagem em um MDF-e",
      "Informar veículo, condutor e percurso",
      "Encerrar o manifesto ao fim da viagem",
    ],
    campos: ["cte.docs", "cte.tomador", "mdfe.condutor", "mdfe.percurso"],
    xml: `<infDoc><infNFe><chave>35250400011122000199550010000001231000001230</chave></infNFe></infDoc>`,
    validacoes: ["REGRA-CHAVE-44", "REGRA-CTE-TOMADOR", "REGRA-MDFE-CONDUTOR"],
    possiveisRejeicoes: ["cstat.pendente.chave", "cstat.pendente.cte", "cstat.pendente.mdfe"],
    solucao: "Corrigir cadastros e chaves antes de manifestar a viagem.",
    procedencia: didatico,
  },
  {
    id: "cen.nfse-outro-municipio",
    nome: "Serviço prestado em outro município",
    objetivo: "Entender o local de incidência do ISS.",
    documento: "nfse",
    participantes: "Prestador em Campinas, tomador em São Paulo",
    operacao: "Prestação de serviço",
    regime: "Regime Normal",
    origem: "Campinas/SP",
    destino: "São Paulo/SP",
    consumidor: "Pessoa jurídica",
    tributacao: ["ISS", "Retenções federais quando aplicáveis"],
    passos: [
      "Identificar prestador e tomador",
      "Escolher o item da lista de serviços",
      "Determinar o município de incidência conforme o tipo de serviço",
      "Aplicar a alíquota do município competente",
      "Definir se há retenção do ISS pelo tomador",
      "Transmitir ao padrão municipal ou nacional",
    ],
    campos: ["nfse.servico"],
    xml: `<servico><itemListaServico><!-- item da lista --></itemListaServico><discriminacao>…</discriminacao></servico>`,
    validacoes: ["REGRA-NFSE-DESCRICAO"],
    possiveisRejeicoes: ["cstat.pendente.nfse"],
    solucao: "Confirmar a regra de incidência do item da lista no município competente.",
    procedencia: didatico,
  },
];

export const cenarioById = new Map(cenarios.map((c) => [c.id, c]));
