import type { CStat, Procedencia } from "./types";

/**
 * CENTRAL DE DIAGNÓSTICO CSTAT.
 *
 * Nenhum código oficial foi inventado. As entradas abaixo são *famílias de
 * rejeição* deste ambiente didático: elas ensinam o raciocínio de diagnóstico
 * (causa → regra → campo → XML → correção) e ficam com o código oficial
 * pendente até ser conferido no manual da versão em uso.
 */
const pendente: Procedencia = {
  status: "pendente",
  fonteId: "moc-nfe",
  vigencia: {
    observacao:
      "Código e descrição oficiais ainda não cadastrados. Conferir na tabela de cStat do manual vigente.",
  },
};

export const cstats: CStat[] = [
  {
    codigo: "cstat.pendente.cfop",
    documento: "nfe55",
    situacao: "CFOP incompatível com a operação declarada",
    causaProvavel:
      "CFOP digitado manualmente ou derivado de tabela desatualizada, sem considerar a UF de destino.",
    regras: ["REGRA-CFOP-DESTINO", "REGRA-CFOP-DEVOLUCAO"],
    campos: ["nfe.cfop"],
    xmlProblema: "<prod><CFOP>5102</CFOP></prod>",
    exemploIncorreto: "Venda de SP para MG com CFOP 5102",
    exemploCorreto: "Venda de SP para MG com CFOP 6102",
    correcao: "Recalcular o CFOP a partir da operação e da UF de destino e retransmitir.",
    impactoErp: "A tabela de operações precisa considerar destino, finalidade e tipo de cliente.",
    checklistSuporte: [
      "Conferir a UF do destinatário no cadastro",
      "Conferir a operação escolhida no pedido",
      "Conferir a tabela de CFOP por operação",
    ],
    procedencia: pendente,
  },
  {
    codigo: "cstat.pendente.calculo",
    documento: "nfe55",
    situacao: "Divergência entre valores calculados e valores informados",
    causaProvavel: "Arredondamento diferente entre o ERP e o gerador do XML, ou valor digitado.",
    regras: ["REGRA-ICMS-VALOR", "REGRA-TOTAL-ITENS"],
    campos: ["nfe.vbc"],
    xmlProblema: "<ICMS00><vBC>2400.00</vBC><pICMS>12.00</pICMS><vICMS>290.00</vICMS></ICMS00>",
    exemploIncorreto: "vICMS 290,00 para base 2.400,00 a 12%",
    exemploCorreto: "vICMS 288,00 para base 2.400,00 a 12%",
    correcao: "Recalcular o imposto no back-end com duas casas decimais e retransmitir.",
    impactoErp: "Centralizar o cálculo e proibir campos de imposto editáveis.",
    checklistSuporte: [
      "Recalcular manualmente base × alíquota",
      "Conferir a política de arredondamento",
      "Conferir rateio de frete e desconto",
    ],
    procedencia: pendente,
  },
  {
    codigo: "cstat.pendente.difal",
    documento: "nfe55",
    situacao: "Grupo de partilha para a UF de destino ausente ou incompleto",
    causaProvavel: "Cliente cadastrado como contribuinte quando é consumidor final não contribuinte.",
    regras: ["REGRA-DIFAL-OBRIGATORIO"],
    campos: ["nfe.difal"],
    xmlProblema: "<!-- grupo ICMSUFDest ausente -->",
    exemploIncorreto: "Venda interestadual a pessoa física sem grupo de partilha",
    exemploCorreto: "Grupo ICMSUFDest preenchido com base, alíquotas e valores",
    correcao: "Corrigir o cadastro do destinatário e recalcular a partilha.",
    impactoErp: "Indicador de contribuinte deve ser campo controlado, não texto livre.",
    checklistSuporte: [
      "Conferir indicador de contribuinte do cliente",
      "Conferir alíquota interna da UF de destino",
      "Conferir se a operação é a consumidor final",
    ],
    procedencia: pendente,
  },
  {
    codigo: "cstat.pendente.ncm",
    documento: "nfe55",
    situacao: "NCM inválido ou inexistente",
    causaProvavel: "Cadastro de produto sem classificação fiscal ou com formato incorreto.",
    regras: ["REGRA-NCM-FORMATO"],
    campos: ["nfe.ncm"],
    xmlProblema: "<prod><NCM>7326</NCM></prod>",
    exemploIncorreto: "NCM com 4 dígitos",
    exemploCorreto: "NCM com 8 dígitos",
    correcao: "Corrigir o NCM no cadastro do produto.",
    impactoErp: "Validar NCM no cadastro e bloquear produto sem classificação.",
    checklistSuporte: ["Conferir o cadastro do produto", "Conferir a tabela de NCM vigente"],
    procedencia: pendente,
  },
  {
    codigo: "cstat.pendente.cst",
    documento: "nfe55",
    situacao: "Situação tributária incompatível com o regime do emitente",
    causaProvavel: "Empresa do Simples enviando CST, ou regime normal enviando CSOSN.",
    regras: ["REGRA-CST-GRUPO", "REGRA-CSOSN-REGIME"],
    campos: ["nfe.cst"],
    exemploIncorreto: "Emitente do Simples com CST 00",
    exemploCorreto: "Emitente do Simples com CSOSN de 3 dígitos",
    correcao: "Ajustar a tributação do produto conforme o regime.",
    impactoErp: "Tributação por produto deve considerar o regime do estabelecimento.",
    checklistSuporte: ["Conferir regime do emitente", "Conferir tributação do produto"],
    procedencia: pendente,
  },
  {
    codigo: "cstat.pendente.referencia",
    documento: "nfe55",
    situacao: "Documento referenciado ausente em operação que o exige",
    causaProvavel: "Devolução lançada sem vincular a nota de origem.",
    regras: ["REGRA-CFOP-DEVOLUCAO"],
    campos: ["nfe.cfop"],
    correcao: "Informar a chave de acesso da nota original.",
    impactoErp: "A tela de devolução deve partir da nota original, não de um lançamento em branco.",
    checklistSuporte: ["Localizar a nota de origem", "Conferir a chave de 44 dígitos"],
    procedencia: pendente,
  },
  {
    codigo: "cstat.pendente.pagamento",
    documento: "nfce65",
    situacao: "Pagamentos não cobrem o total da venda",
    causaProvavel: "Cupom finalizado com saldo em aberto no PDV.",
    regras: ["REGRA-PAG-SOMA"],
    campos: ["nfce.pag"],
    correcao: "Registrar o pagamento faltante antes de transmitir.",
    impactoErp: "Bloquear a finalização com saldo devedor.",
    checklistSuporte: ["Somar os meios de pagamento", "Conferir o troco informado"],
    procedencia: { ...pendente, fonteId: "mo-nfce" },
  },
  {
    codigo: "cstat.pendente.qrcode",
    documento: "nfce65",
    situacao: "QR Code ausente ou inconsistente",
    causaProvavel: "CSC incorreto, ambiente trocado ou versão de algoritmo diferente.",
    regras: [],
    campos: ["nfce.qrcode"],
    correcao: "Conferir CSC e ambiente configurados no back-end.",
    impactoErp: "CSC nunca deve ficar no PDV em texto claro.",
    checklistSuporte: ["Conferir ambiente", "Conferir identificador do CSC", "Conferir versão do algoritmo"],
    procedencia: { ...pendente, fonteId: "mo-nfce" },
  },
  {
    codigo: "cstat.pendente.nfse",
    documento: "nfse",
    situacao: "Rejeição municipal de NFS-e",
    causaProvavel:
      "Código de serviço inválido para o município, descrição insuficiente ou alíquota fora da faixa municipal.",
    regras: ["REGRA-NFSE-DESCRICAO"],
    campos: ["nfse.servico"],
    correcao: "Conferir o código do serviço no município e detalhar a discriminação.",
    impactoErp: "Manter o cadastro de serviços por município.",
    checklistSuporte: [
      "Conferir município de incidência",
      "Conferir código municipal do serviço",
      "Conferir regime do prestador",
    ],
    procedencia: { ...pendente, fonteId: "nfse-nacional" },
  },
  {
    codigo: "cstat.pendente.chave",
    documento: "cte57",
    situacao: "Chave de documento vinculado inválida",
    causaProvavel: "Importação parcial do XML ou digitação manual.",
    regras: ["REGRA-CHAVE-44"],
    campos: ["cte.docs"],
    correcao: "Reimportar o XML da nota transportada.",
    impactoErp: "Validar chave na importação, com dígito verificador.",
    checklistSuporte: ["Conferir tamanho da chave", "Conferir dígito verificador"],
    procedencia: { ...pendente, fonteId: "mo-cte" },
  },
  {
    codigo: "cstat.pendente.cte",
    documento: "cte57",
    situacao: "Tomador do serviço inconsistente",
    causaProvavel: "Condição de frete não refletida no documento.",
    regras: ["REGRA-CTE-TOMADOR"],
    campos: ["cte.tomador"],
    correcao: "Selecionar o participante que contratou o transporte.",
    impactoErp: "Derivar o tomador da condição de frete do pedido.",
    checklistSuporte: ["Conferir condição de frete", "Conferir participantes informados"],
    procedencia: { ...pendente, fonteId: "mo-cte" },
  },
  {
    codigo: "cstat.pendente.cteos",
    documento: "cteos67",
    situacao: "Grupo incompatível com a modalidade do CT-e OS",
    causaProvavel: "Uso de leiaute de carga em prestação de transporte de pessoas ou valores.",
    regras: ["REGRA-CTEOS-MODALIDADE"],
    campos: ["cteos.modalidade"],
    correcao: "Selecionar a modalidade correta antes de preencher.",
    impactoErp: "Separar telas por modalidade.",
    checklistSuporte: ["Conferir a modalidade", "Conferir grupos preenchidos"],
    procedencia: { ...pendente, fonteId: "mo-cte" },
  },
  {
    codigo: "cstat.pendente.mdfe",
    documento: "mdfe58",
    situacao: "Manifesto com condutor, veículo ou percurso inconsistente",
    causaProvavel: "CPF inválido, placa fora do cadastro ou UF final divergente dos documentos.",
    regras: ["REGRA-MDFE-CONDUTOR", "REGRA-MDFE-PERCURSO"],
    campos: ["mdfe.condutor", "mdfe.percurso"],
    correcao: "Corrigir o cadastro envolvido e reemitir ou usar evento, conforme o caso.",
    impactoErp: "Validar cadastros de motorista e veículo antes da viagem.",
    checklistSuporte: ["Conferir CPF do condutor", "Conferir placas", "Conferir UF inicial e final"],
    procedencia: { ...pendente, fonteId: "mo-mdfe" },
  },
  {
    codigo: "cstat.pendente.evento",
    documento: "eventos",
    situacao: "Evento de manifestação recusado",
    causaProvavel: "Justificativa insuficiente, evento duplicado ou fora de sequência.",
    regras: ["REGRA-MANIF-JUSTIFICATIVA", "REGRA-MANIF-DUPLICIDADE"],
    campos: ["evento.manifestacao"],
    correcao: "Ajustar a justificativa ou conferir o histórico antes de reenviar.",
    impactoErp: "Guardar protocolo e retorno bruto de cada evento.",
    checklistSuporte: ["Conferir histórico da nota", "Conferir texto da justificativa"],
    procedencia: pendente,
  },
];

export const cstatByCodigo = new Map(cstats.map((c) => [c.codigo, c]));
